Azure-Samples/communication-services-web-calling-tutorial

- Project/src/MakeCall/MakeCall.js
Ask for device permissions after logging in.
```
[ ] Yes
[ X ] No
```
```
[ ] Bugfix
[ ] Feature
[ X ] Refactoring (no functional changes, no api changes)
```
```
After provisioning user token and initializing sdk, browser will prompt user for device permissions. If permissions are already granted then browser will not prompt user for permissions.
```
* ...
> ask for device permissions after logging in

- Project/package-lock.json
- Project/package.json
- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/RemoteParticipantCard.js
- Project/src/MakeCall/StreamMedia.js
Clean up / refactor code
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
```
Read the readme to setup and run project
> cleanup code

- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/MakeCall.js
- Project/src/Utils/Utils.js
Update sample's sdk dependencies to current version 1.0.0-beta-4
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* Check updated properties for 1.0.0-beta-4 work properly.
> Update sdks and rename properties according to changes.

- Project/.gitignore
- Project/package-lock.json
- Project/src/App.css
- Project/src/App.js
- Project/src/MakeCall/AddParticipantPopover.js
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/Login.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/RemoteParticipantCard.js
- Project/src/MakeCall/StreamMedia.js
- Project/webpack.config.js
Update to calling package version Beta4
```
[ X ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[ X ] Other... Please describe:
Update to new package version
```
> Beta4 updates

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/IncomingCallCard.js
- Project/src/MakeCall/MakeCall.js
- Project/webpack.config.js
* ...
```
[ ] Yes
[ X ] No
```
```
[ ] Bugfix
[ ] Feature
[ X ] Refactoring (no functional changes, no api changes)
```
> Refactor code

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/MakeCall.js
Fix devices check
```
[ ] Yes
[ X ] No
```
```
[ X ] Bugfix
[ ] Feature
```
> fix devices check

- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/CallCard.js
Update to beta.7
```
[ ] Yes
[ X ] No
```
```
[ ] Bugfix
[ ] Feature
[ X ] Other... Please describe:
```
> update to beta.7

- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/StreamMedia.js
Downgrade to beta.6 becuase beta.7 is broken and it is currently being fixed.
```
[ ] Yes
[ X ] No
```
```
[ X ] Bugfix
[ ] Feature
```
> downgrade to beta.6

- Project/src/MakeCall/MakeCall.js
Fix pstn call options
```
[ ] Yes
[ X ] No
```
```
[ X ] Bugfix
[ ] Feature
```
> fix pstn call options

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/RemoteParticipantCard.js
- Project/src/MakeCall/StreamMedia.js
Fix responsiveness
```
[ ] Yes
[ X ] No
```
```
[ X ] Bugfix
[ ] Feature
```
> fix responsiveness

- Project/src/MakeCall/MakeCall.js
fix for seeing incoming call buttons after incoming call
```
[ ] Yes
[ X ] No
```
```
[ X ] Bugfix
[ ] Feature
```
> fix for seeing incoming call buttons after incoming call

- Project/package-lock.json
- Project/package.json
- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/IncomingCallCard.js
- Project/src/MakeCall/LocalVideoPreviewCard.js
- Project/src/MakeCall/Login.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/RemoteParticipantCard.js
- Project/src/MakeCall/StreamMedia.js
- Project/src/Utils/Utils.js
- Project/webpack.config.js
Update to version 1.0.0
```
[ X ] Yes
[ ] No
```
```
[ ] Bugfix
[ X ] Feature
```
> Update to 1.0.0

- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/MakeCall.js
Update to 1.0.1-beta.1
```
[ ] Yes
[ X ] No
```
```
[ ] Bugfix
[ X ] Feature
```
> update to 1.0.1-beta.1

- Project/src/MakeCall/MakeCall.js
Ask for device permissions separately
```
[ ] Yes
[ X ] No
```
```
[ X ] Bugfix
[ ] Feature
```
> Ask for device permissions separately

- Project/package-lock.json
- Project/package.json
Update to @azure/communication-calling v1.0.1-beta.2
```
[ ] Yes
[ X ] No
```
> Update to calling v1.0.1-beta.2

- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/MakeCall.js
* Updated communication-calling to 1.1.0-beta.1 version
* Show UFDs when call is in progress
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
git clone https://github.com/onlysumon/communication-services-web-calling-tutorial.git
cd communication-services-web-calling-tutorial
git checkout sharif/ufds
npm install
```
```
```
* `speakingWhileMicrophoneIsMuted` call diagnostic event when call is muted.
> 1.2.0-beta.1 and show UFDs when call is active

- Project/package.json
Update to calling v 1.2.2-beta.1
```
[ ] Yes
[ X ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update to 1.2.2-beta.1

- Project/package.json
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/MakeCall.js
```
[] Yes
[X] No
```
```
[X] Bugfix
[X] Feature
[X] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
```
> 1.3.1 beta.1 upgrade and feature additions

- Project/package-lock.json
- Project/package.json
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> changing to 1.3.2 beta new released calling SDK

- Project/src/MakeCall/Login.js
- Project/src/MakeCall/MakeCall.js
This change allows tagging usage sessions of this app
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
> Have way to tag usage sessions

- Project/src/MakeCall/MakeCall.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Render permission state to the UI

- Project/package.json
- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/DebugInfoCard.js
- Project/src/MakeCall/MakeCall.js
- Project/src/Utils/Utils.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> adding debug info feature

- Project/src/MakeCall/MakeCall.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Added a card to display environment information

- Project/package-lock.json
- Project/package.json
Update to 1.5.4-beta.1
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update to 1.5.4-beta.1

- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Audio media access prototype using the new APIs

- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/CallCard.js
Added new speaker icon next to the mute icon to demonstrate the mute/unmute incoming audio feature. 
```
[ ] Yes
[ X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
Join call.
When click on the mute speaker icon then the incoming audio should be muted (not call audio will be played).
When click on the unmute speaker icon then the incoming audio should start playing.
```
* ...
> Mute / Unmute Incoming Audio

- Project/src/App.css
- Project/src/MakeCall/StreamRenderer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> loading spinner

- Project/package-lock.json
- Project/package.json
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update to 1.6.2-beta.2

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> added volume indicator

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/VolumeVisualizer.js
* ...
```
[ ] Yes
[ x ] No
```
```
[x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> dispose local audio stream

- Project/src/MakeCall/CallCard.js
* Add MediaStats log switch on UI
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Add MediaStats log switch on UI

- Project/package.json
- Project/src/App.css
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Csandjon/1.9.0 alpha.1

- Project/package.json
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/CustomVideoEffects.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/RawMediaStream.js
- Project/src/MakeCall/StreamRenderer.js
Added button to add effect to local and remote video stream.
* ...
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
```
```
cd [repo-name]
npm install
```
Start a video call with multiple participants and click on buttons to add or remove b/w effects.
```
```
Verify the video rendered sees a b/w filter or sending a video with b/w filter.
> Raw media stream

- Project/src/App.css
- Project/src/MakeCall/MakeCall.js
Added Pre Call Diagnostics Api and render resultsd on page.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
Run the app, go to Pre Call Diagnostics panel and click on Run Pre Call Diagnostics button.
```
cd [repo-name]
npm install
```
Run the app, go to Pre Call Diagnostics panel and click on Run Pre Call Diagnostics button.
Results should be rendered on the page after call finished rought 30 secs
```
```
Results should be rendered on the page.
> Pre call diagnostics

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/VolumeVisualizer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Adding volume indicator and transform outgoing audio

- Project/src/MakeCall/VolumeVisualizer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix remote volume indicator

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/RemoteParticipantCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Adding multiple tabs feature

- Project/package.json
- Project/src/MakeCall/VolumeVisualizer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Updating to beta 1.10 and volumeIndicator refactoring

- Project/package.json
- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/FunctionalStreamRenderer.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/RawVideoAccess/CustomVideoEffects.js
- Project/src/MakeCall/RemoteParticipantCard.js
- Project/src/MakeCall/StreamRenderer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Video Rendering limit

- Project/src/MakeCall/FunctionalStreamRenderer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix loading spinner not showing

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/MakeCall.js
Introducing capabilities feature to get the capabilities of a local participant and listen to capabilities update.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
Steps	Action	Expected result	Attachments
1.	ACS User joins an ACS Room
2.	ACS user registers for capabilities feature	
3.	ACS user successfully get's the users capabilities in the meeting setup
4.	ACS user registers listeners to listen to capability updates
5.	ACS user receives …
```
> Capabilities feature

- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/MediaConstraint.js
* Add send max height resolution video constraint UI setting.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
1. select video resolution before making a call or accepting a call
2. join/make/accept a call with video
3. check sent resolution on sender side
```
* if video resolution constraint is set on the sender side, the height of sent resolution should not exceed the constraint value.
only support when …
> Add video constraints UI

- Project/package-lock.json
- Project/package.json
Update package to use 11 beta so it not breaks
> update package to 11 beta

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/CurrentCallInformation.js
- Project/src/MakeCall/FunctionalStreamRenderer.js
- Project/src/MakeCall/RawVideoAccess/CustomVideoEffects.js
- Project/src/MakeCall/VideoReceiveStats.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Optimal video count changes

- Project/src/MakeCall/VideoReceiveStats.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Removing unnecesary console log

- Project/src/MakeCall/IncomingCallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> 1:1 video Bug fix

- Project/src/MakeCall/FunctionalStreamRenderer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fixing loading spinner issue

- Project/package-lock.json
- Project/package.json
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> update sdk version

- Project/src/MakeCall/CallSurvey.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/StarRating.js
Add Call Survey sample to the code
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> adding call survey sample

- Project/src/MakeCall/StarRating.js
* Show rating title 1, 2, 3, 4 or 5 on hovering over the start
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* Hover over the rating star to see the value 1 to 5
> Show rating title 1 to 5

- Project/src/MakeCall/CallSurvey.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/StarRating.js
* Adding call survey sample to alpha
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* You should have survey option at the end of the call
> Adding call survey sample to Alpha

- Project/src/MakeCall/CallSurvey.js
* screenshareRating typo fix
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Screenshare Rating Typo Fix

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/FunctionalStreamRenderer.js
- Project/src/MakeCall/RawVideoAccess/CustomVideoEffects.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> 3x3 rendering

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/FunctionalStreamRenderer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> First rendering approach

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/FunctionalStreamRenderer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> mem leak fix

- Project/src/App.css
- Project/src/MakeCall/CallCaption.js
- Project/src/MakeCall/CallCard.js
* Sample shows how to use ACS Caption feature
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> ACS Captions

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix for participant listn ot showing first participant that joins'

- Project/package-lock.json
- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> remoteParticipants setState callback

- Project/src/App.css
- Project/src/App.js
- Project/src/MakeCall/Login.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/NetworkConfiguration/ProxyConfiguration.js
- Project/src/MakeCall/NetworkConfiguration/TurnConfiguration.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix login layout

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> clean up property usage on call card

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/LocalVideoPreviewCard.js
- Project/src/MakeCall/Login.js
- Project/src/MakeCall/NetworkConfiguration/ProxyConfiguration.js
- Project/src/MakeCall/NetworkConfiguration/TurnConfiguration.js
- Project/src/MakeCall/RawVideoAccess/CustomVideoEffects.js
- Project/src/MakeCall/VideoEffects/VideoEffectsContainer.js
- Project/src/MakeCall/VideoEffects/VideoEffectsImagePicker.js
- Project/src/Utils/Utils.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Local SS preview and raw SS

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Handle screen share off from native stop button

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/RawVideoAccess/CustomVideoEffects.js
- Project/src/Utils/Utils.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix black and white screen share effects

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/RawVideoAccess/CustomVideoEffects.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> minor ui fixes

- Project/src/MakeCall/CallCaption.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix captions for acs

- Project/src/MakeCall/Login.js
- Project/src/Utils/Utils.js
- Project/webpack.config.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Login with custom user id

- Project/src/App.css
- Project/src/MakeCall/VolumeVisualizer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix volume indicator

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/FunctionalStreamRenderer.js
- Project/src/MakeCall/RawVideoAccess/CustomVideoEffects.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Clean up customvideoeffects component

- Project/src/MakeCall/CallCaption.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix ACS captions in teams meetings

- Project/package-lock.json
- Project/package.json
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update to calling 1.15.1-beta.1

- Project/src/MakeCall/DataChannelCard.js
- Project/src/MakeCall/LocalVideoPreviewCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> check if feature exists

- Project/package.json
- Project/src/MakeCall/Login.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix for CTE login

- Project/src/MakeCall/RemoteParticipantCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> updated lobby api

- Project/src/MakeCall/MakeCall.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Add call agent to window

- Project/package.json
- Project/webpack.config.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> node 14 does not support atob so moving to Buffer class

- Project/src/App.css
- Project/src/MakeCall/CallCaption.js
* GA Teams interop captions rework.
> GA Teams Captions implemented

- Project/src/MakeCall/Login.js
* Show the call agent connection state to inform participant about their connectivity to the ACS signaling backend. This connection state will confirm whether the participant can make or receive calls.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* UI should show `Connection status`: `Connecting` or `Connected` or `Disconnected`
> Call agent connection state

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix text typo

- Project/src/App.css
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> default zoom

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix app bug

- Project/src/App.css
- Project/src/App.js
- Project/src/MakeCall/Login.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> css updates

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/MediaConstraint.js
* User can set media constraints before starting
* Can change it while on call
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Media constraints video height, bitrate and framerate

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Show media constraints UI if API is available

- Project/src/App.css
- Project/src/App.js
- Project/src/MakeCall/Login.js
- Project/src/MakeCall/MakeCall.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> structure update

- Project/src/MakeCall/Login.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix call client options position

- Project/src/App.css
- Project/src/App.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> allow multi use login

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/FunctionalStreamRenderer.js
- Project/src/MakeCall/Login.js
- Project/src/MakeCall/MakeCall.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix dominant speaker mode video

- README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> updat readme

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/RemoteParticipantCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Introduce UI changes for Mute Others feature

- Project/clientConfig.json
- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/CallSurvey.js
* Call survey example with text input
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Call survey with free form text

- .vscode/settings.json
- Project/.babelrc
- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/CallSurvey.js
- Project/src/MakeCall/Login.js
- Project/webpack.config.js
- README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update for Node 18

- Project/src/MakeCall/CallCard.js
* Reaction Feature introduced for testing 
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Meeting Reaction feature integrated 

- Project/src/MakeCall/CallCard.js
* Showing correct sender identifier for reaction
```
[ ] Yes
[ ] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> [Bugfix] Showing correct sender identifier for reaction

- Project/src/MakeCall/CallCard.js
* Update reaction feature initiation API change
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update reaction feature initiation API change

- Project/src/MakeCall/CallCaption.js
PSTN numbers have a plus prefix. 
ClassNames are generated using the mri, so need to also remove plus symbol as it is not a supported symbol in ClassNames.
> Bugfix for captions with pstn numbers, remove plus symbol from className

- Project/package-lock.json
- Project/package.json
* Update communication-calling version to 1.18.1-beta.1
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update communication-calling version

- Project/src/MakeCall/CallCard.js
* Reaction receiver attribute update
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> [Bugfix] Reaction receiver attribute update

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ x ] No
```
This includes Teams Meeting Audio conferencing feature.
```
[ ] Bugfix
[ x ] Feature
```
> Included Audio Conferencing feature

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Bug Fix: Webcam light on with Rooms Consumer Role

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix bug with screen share capabilities

- Project/package-lock.json
- Project/package.json
* Updating the dependency for calling sdk
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update Calling SDK version

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
* Implement the PPTLive
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
cd [repo-name]
npm install
```
```
```
*
> Implement the PPTLive

- Project/src/App.css
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update the pptLive size

- Project/src/MakeCall/CallCard.js
* Allow participants to turn on mic, camera, screenshare etc. when the capability feature is not available.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Check capabilities feature not supported

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update PPT logic

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix the screen sharing. 

- Project/src/MakeCall/CallSurvey.js
* Each rating issues should be from the predefined types. Empty string is not expected an value.
```
[ ] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Rating issues pass expected values only

- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/Lobby.js
- Project/src/MakeCall/RemoteParticipantCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Enable InLobby list and admit all

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix Screen Share and PPTLive logic

- Project/src/MakeCall/CallCard.js
* Addressing the bug: https://skype.visualstudio.com/SPOOL/_workitems/edit/3503710
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Showing only the most recent error for reaction in callMessage

- Project/package-lock.json
- Project/package.json
- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/CurrentCallInformation.js
- Project/src/MakeCall/Lobby.js
- Project/src/MakeCall/RemoteParticipantCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Display participant ids

- Project/src/MakeCall/RemoteParticipantCard.js
* ...
Fix lower hand for remote participant.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix lower hand for remote participant

- Project/src/MakeCall/CallCard.js
* Rename for the capability API for reaction feature.
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Capability rename for reaction feature

- Project/src/App.css
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix buttons

- Project/src/Constants.js
- Project/src/MakeCall/Login.js
- Project/src/MakeCall/MakeCall.js
* Get display name (dn), meeting link (ml), video and mic option from the URL
* Login with pre-filled display name option by one button click
* Auto Join meeting with video and mic option
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> One click login and join meeting

- Project/package-lock.json
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/ParticipantMenuOptions.js
- Project/src/MakeCall/RemoteParticipantCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Disable raise hand and spotlight while call on hold

- Project/src/MakeCall/CallCaption.js
Add support to stop ACS closed captions
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Add support to stop ACS closed captions
```
> Add support to stop ACS closed captions

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> enhanced PSTN

- Project/package.json
- Project/src/MakeCall/IncomingCallCard.js
- Project/src/MakeCall/MakeCall.js
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Custom context

- Project/src/MakeCall/MakeCall.js
* Select default microphone and speakers when making call.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Default mic and speaker

- Project/package-lock.json
- Project/package.json
* Communication calling version updated to 1.26.1-beta.1
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Updating to version 1.26.1-beta.1

- Project/src/MakeCall/CallCard.js
* Adds a message bar for a local participant who has been soft muted by another participant. 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* When local participant has been muted by others, a message bar appears
> Add message when mutedByOthers event received

- Project/src/MakeCall/AudioEffects/AudioEffectsContainer.js
* Refresh the UI when effects started or stopped
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Audio effects UI fix

- Project/package-lock.json
- Project/package.json
* Communication calling and effect package version update
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Communication calling and effect package update

- Project/src/MakeCall/CallCard.js
* updates server muted message that pops up when participant is muted by others (soft mute feature) or server muted as part of their role (eg. Rooms consumer)
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* Verify message pops up when user is muted by others or is a consumer in a Room.
> Update mutedByOthers message

- Project/src/MakeCall/MakeCall.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> window ufds

- Project/src/MakeCall/VideoEffects/VideoEffectsContainer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix for bg replacement

- Project/src/App.css
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/FunctionalStreamRenderer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> isPinningActive

- Project/src/App.js
* Default UI Fabric Icon is returning 404, using specific CDN to fix the issue.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Use specific CDN for UI Fabric Icon

- Project/package-lock.json
- Project/package.json
- Project/src/App.js
- Project/src/MakeCall/AddParticipantPopover.js
- Project/src/MakeCall/CallCaption.js
- Project/src/MakeCall/CallCard.js
- Project/src/MakeCall/CallSurvey.js
- Project/src/MakeCall/DataChannelCard.js
- Project/src/MakeCall/Lobby.js
- Project/src/MakeCall/Login.js
- Project/src/MakeCall/MakeCall.js
- Project/src/MakeCall/MediaConstraint.js
- Project/src/MakeCall/NetworkConfiguration/ProxyConfiguration.js
- Project/src/MakeCall/NetworkConfiguration/TurnConfiguration.js
- Project/src/MakeCall/RawVideoAccess/CustomVideoEffects.js
- Project/src/MakeCall/RealTimeTextCard.js
- Project/src/MakeCall/RemoteParticipantCard.js
- Project/src/MakeCall/Section.js
- Project/src/MakeCall/StarRating.js
- Project/src/MakeCall/VideoEffects/VideoEffectsContainer.js
- Upgrade fluentui/react from 7.158.1 to 8.122.9 
- Fix VideoOff2 icon by registering SVG VideoOff2Icon as VideoOff2
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
> Upgrade fluentui/react to 8.122.9 and fix VideoOff2 icon

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix app's pinning logic

- Project/src/MakeCall/CallCard.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> dont init RRT for cte

- Project/src/MakeCall/FunctionalStreamRenderer.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix renderer dispose

- Project/src/MakeCall/MakeCall.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> ufdMessage remove iteself after 15 seconds

- Project/oAuthConfig.js
- Project/package-lock.json
- Project/package.json
- Project/src/MakeCall/Login.js
- Project/src/Utils/Utils.js
- Project/webpack.config.js
* Code sample to showcase the Entra ID auth
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* User can login using Entra ID
* Make and receive calls
* Join meeting
* Join group calls
> Entra ID Auth
