Azure-Samples/communication-services-web-calling-tutorial

Project/src/App.css
Project/src/MakeCall/CallCard.js
Project/src/MakeCall/StreamRenderer.js
Project/src/MakeCall/VideoReceiveStats.js

* Fix mediastats log switch button 
* Add video stream stats overlay on video renderer when mediastats log switch is on
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* click the right most button on CallCard, we should see an overlay showing mediastats on video renderer, also see mediastats in console log every second.

Add video stats overlay on video renderer

---

Project/src/MakeCall/MakeCall.js

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

added debug info dump button

---

Project/src/MakeCall/MakeCall.js

This feature will allow the ACS and CTE users to join the Teams Meeting via MeetingId and Passcode.
```
[ ] Yes
[ X] No
```
Adding a new field meeting passcode
```
[ ] Bugfix
[x] Feature
```
Create a Teams meeting. Get the meeting id and passcode for the meeting link.
1) Login as ACS user in the sample app and try to join the meeting with meetingid and passcode. The ACS user should be able to join the meeting.
2) Login as CTE user and join the meeting with meeting id and passcode. CTE user should be able to join the meeting.
```
git clone …
```

added changes for meetingId and passcode

---

Project/src/MakeCall/CallCard.js
Project/src/MakeCall/MakeCall.js

* Capability read for reaction applied in the API usage for reaction API
* For not allowed scenario - the API usage would return an error 
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* Check for below error message when reaction button is tapped but not allowed in meeting.

Capability applied for Reaction API usage

---

Project/src/MakeCall/CallCard.js

This PR fixes issues where the options to start/stop spotlight was disabled for a participant with presenter role. The fix was to update the capabilities property whenever there's an update to the capability features.
This PR also includes the fix to make 'stop spotlight' option available to participant with attendee role.
* ...
```
[ ] Yes
[ x] No
```
```
[x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

fix for spotlight capability

---

Project/src/MakeCall/MakeCall.js

With new coming feature of thread ID integration on web calling SDK, Contoso App can leverage API to place a CTE group call without providing thread ID. So we do the corresponding change on public sample as well to allow user place a CTE group call without passing on thread ID.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...

Make thread ID parameter as optional when placing a CTE group call

---

Project/src/MakeCall/CallCard.js

Hide captions button when not connected to a call. 
Adding captions bot participant is only possible once user is connected to the call.

HIde captions button when not connected to a call

---

Project/src/MakeCall/CallCard.js
Project/src/MakeCall/MakeCall.js
Project/src/MakeCall/RemoteParticipantCard.js

* Remote UFD feature
* Collapsible participants list on the left side of the screen
* Show remote participants ID
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...

Remote UFD feature and UI updates

---

Project/src/App.css
Project/src/MakeCall/CallCard.js
Project/src/MakeCall/Lobby.js
Project/src/MakeCall/RemoteParticipantCard.js

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Hide lobby admit/reject when user doesn't have ability to manage lobby

---

Project/src/MakeCall/CallCard.js
Project/src/MakeCall/RemoteParticipantCard.js

* Blocks Mute All button from appearing if user does not have the capability to muteOthers
* Logs console error from clicking on mute icon of remote participant if user does not have the capability to muteOthers
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
1. Login in 2 tabs as ACS users 
1. Create a Room with 1 user as Presenter, 1 user as Attendee
1. Presenter has Mute All button, can mute all …

Add muteOthers capability to Call and RemoteParticipant

---

Project/src/MakeCall/CallCard.js
Project/src/MakeCall/FunctionalStreamRenderer.js
Project/src/MakeCall/StreamRenderer.js
Project/src/MakeCall/VideoReceiveStats.js

* The rtt value is not available for the incoming videos due to the mediastats layout change.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```

Fix rtt stats for incoming videos

---

Project/src/MakeCall/CallCard.js
Project/src/MakeCall/Lobby.js

Fix the bug: [In-lobby participant count and "Admit all participants" button stays visible after all in-lobby participants have already been admitted to the call](https://skype.visualstudio.com/SPOOL/_deliveryplans/plan/afec522a-2dee-4dc2-a6e6-8873cabda33b?System.AssignedTo=tinaharter%40microsoft.com)
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix lobby admitall button and lobby participants count

---

Project/src/MakeCall/CallCard.js

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Updating the name of the API - Explicit Consent

---

Project/src/App.css
Project/src/MakeCall/CallCaption.js
Project/src/MakeCall/CallCard.js
Project/src/MakeCall/RealTimeTextCard.js

* Add RealTimeText sample to the app
* Backwards compatible as it checks to see if the feature is available first before actioning or showing buttons
* Added small fix to CallCaptions to the PR as well as caption language was not being set correctly
Showcasing label
Showcasing Feature 
Showcasing banner warning when trying to close/hide rtt
```
[ ] Yes
[x] No
```
```
[o] Bugfix
[o] Feature
```

Add RealTimeText to sample

---

Project/src/App.css
Project/src/MakeCall/CallCard.js
Project/src/MakeCall/RemoteParticipantCard.js

* ...
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* Login user can receive mic/camera hard muted events and show mic/camera disabled:
* Can see remote participants hard mute states:
* When user has organizer or presenter role, can Disable/Enable other attendees' mic/camera.
* When user has forbidOthersAudio/forbidOthersVideo capabilities, can Disable/Enable meeting setting attendees' audio/video.

Hard mute feature support to sample app

---

Project/src/App.css
Project/src/MakeCall/CallCard.js
Project/src/MakeCall/FunctionalStreamRenderer.js

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

dual pinning

---

Project/src/MakeCall/CallCard.js

* ...
This PR to fix logic showing video off icon when user can turn on video.
There is an existing problem that videoOff2 icon is not working from CDN, that is separate issue.
Problem: when user has video off and user cannot turn on video, we showed two icons:
Fix is to show one of the 3 icons depending on states.
1.this.state.canOnVideo && this.state.videoOn
2. this.state.canOnVideo && !this.state.videoOn
3.!this.state.canOnVideo
```
[ ] Yes
[ x] No
```
```
[ x] Bugfix
[ ] Feature
```
1.When user has video on:
2. When user has video off, can turn on …

Fix logic when video off and user can turn on video

---

Project/src/MakeCall/CallCard.js
Project/src/MakeCall/RemoteParticipantCard.js

In Teams meeting, if Teams user edited display name, the edited display name needs to be shown in the RemoteParticipantCard component.
Before display name update:
After display name update:
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Show edited display name

---

Project/src/MakeCall/MakeCall.js

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

window deviceManager

---

Project/package-lock.json
Project/package.json
Project/src/MakeCall/MakeCall.js
Project/src/Utils/Utils.js
Project/webpack.config.js

* Update package versions to calling 1.34.1-beta.2, rooms 1.2.0
* Addition of Rooms panel in sample which allows user to manage a Room in detail such as: 
* Create a Room with multiple participants in any role 
* Update a participant's role in the Room 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
Test the UI functionality for this panel

Add more Rooms functionality with new Manage Rooms panel

---

Project/package-lock.json
Project/package.json
Project/src/App.css
Project/src/MakeCall/CallCard.js
Project/src/MakeCall/RemoteParticipantCard.js

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix participant panel when rendering videos

---

Project/oAuthConfig.js
Project/src/Utils/Utils.js
Project/webpack.config.js

* Move auth config to server side to have single source of truth
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Move auth config to server side

---

Project/src/MakeCall/CallCard.js
Project/src/MakeCall/CurrentCallInformation.js

* ...
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

#4240940: Adding ovc change reason
